authors = ["Mateusz Kapusta and Piotr PÅ‚onka"]
name = "Verona"
uuid = "7d88ae71-11e1-4e37-be52-50fe39e219fb"
version = "0.1.0"

[compat]
CUDA = "5.6.1"
HDF5 = "0.17.2"
KernelAbstractions = "0.9.33"
LinearAlgebra = "1.11.0"
MPI = "0.20.22"
StaticArrays = "1.9.11"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
